using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace Redbox.HAL.Common.GUI.Functions
{
    public class GearAndMotorProperties : Form
    {
        private Button button1;
        private Button button2;
        private IContainer components;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private GroupBox groupBox4;
        private GroupBox groupBox5;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label12;
        private Label label13;
        private Label label14;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private TextBox textBox1;
        private TextBox textBox10;
        private TextBox textBox11;
        private TextBox textBox12;
        private TextBox textBox13;
        private TextBox textBox14;
        private TextBox textBox2;
        private TextBox textBox3;
        private TextBox textBox4;
        private TextBox textBox5;
        private TextBox textBox6;
        private TextBox textBox7;
        private TextBox textBox8;
        private TextBox textBox9;

        public GearAndMotorProperties()
        {
            InitializeComponent();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null)
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            button1 = new Button();
            button2 = new Button();
            groupBox1 = new GroupBox();
            groupBox2 = new GroupBox();
            groupBox3 = new GroupBox();
            groupBox4 = new GroupBox();
            groupBox5 = new GroupBox();
            label1 = new Label();
            label2 = new Label();
            label3 = new Label();
            label4 = new Label();
            label5 = new Label();
            label6 = new Label();
            label7 = new Label();
            label8 = new Label();
            textBox1 = new TextBox();
            textBox2 = new TextBox();
            textBox3 = new TextBox();
            textBox4 = new TextBox();
            textBox5 = new TextBox();
            textBox6 = new TextBox();
            textBox7 = new TextBox();
            textBox8 = new TextBox();
            label9 = new Label();
            label10 = new Label();
            label11 = new Label();
            label12 = new Label();
            label13 = new Label();
            label14 = new Label();
            textBox9 = new TextBox();
            textBox10 = new TextBox();
            textBox11 = new TextBox();
            textBox12 = new TextBox();
            textBox13 = new TextBox();
            textBox14 = new TextBox();
            groupBox1.SuspendLayout();
            groupBox2.SuspendLayout();
            groupBox3.SuspendLayout();
            groupBox4.SuspendLayout();
            groupBox5.SuspendLayout();
            SuspendLayout();
            button1.Location = new Point(140, 530);
            button1.Name = "button1";
            button1.Size = new Size(75, 56);
            button1.TabIndex = 1;
            button1.Text = "Ok";
            button1.UseVisualStyleBackColor = true;
            button2.Location = new Point(303, 530);
            button2.Name = "button2";
            button2.Size = new Size(75, 56);
            button2.TabIndex = 2;
            button2.Text = "Cancel";
            button2.UseVisualStyleBackColor = true;
            groupBox1.Controls.Add(textBox4);
            groupBox1.Controls.Add(textBox3);
            groupBox1.Controls.Add(textBox2);
            groupBox1.Controls.Add(textBox1);
            groupBox1.Controls.Add(label4);
            groupBox1.Controls.Add(label3);
            groupBox1.Controls.Add(label2);
            groupBox1.Controls.Add(label1);
            groupBox1.Location = new Point(27, 24);
            groupBox1.Name = "groupBox1";
            groupBox1.Size = new Size(200, 142);
            groupBox1.TabIndex = 3;
            groupBox1.TabStop = false;
            groupBox1.Text = "Gear X Properties";
            groupBox2.Controls.Add(textBox8);
            groupBox2.Controls.Add(textBox7);
            groupBox2.Controls.Add(textBox6);
            groupBox2.Controls.Add(textBox5);
            groupBox2.Controls.Add(label8);
            groupBox2.Controls.Add(label7);
            groupBox2.Controls.Add(label6);
            groupBox2.Controls.Add(label5);
            groupBox2.Location = new Point(292, 24);
            groupBox2.Name = "groupBox2";
            groupBox2.Size = new Size(214, 142);
            groupBox2.TabIndex = 4;
            groupBox2.TabStop = false;
            groupBox2.Text = "Gear Y Properties";
            groupBox3.Controls.Add(textBox11);
            groupBox3.Controls.Add(textBox10);
            groupBox3.Controls.Add(textBox9);
            groupBox3.Controls.Add(label11);
            groupBox3.Controls.Add(label10);
            groupBox3.Controls.Add(label9);
            groupBox3.Location = new Point(15, 32);
            groupBox3.Name = "groupBox3";
            groupBox3.Size = new Size(200, 114);
            groupBox3.TabIndex = 5;
            groupBox3.TabStop = false;
            groupBox3.Text = "Init Speed";
            groupBox4.Controls.Add(groupBox5);
            groupBox4.Controls.Add(groupBox3);
            groupBox4.Location = new Point(27, 185);
            groupBox4.Name = "groupBox4";
            groupBox4.Size = new Size(491, 163);
            groupBox4.TabIndex = 6;
            groupBox4.TabStop = false;
            groupBox4.Text = "Motor X ";
            groupBox5.Controls.Add(textBox14);
            groupBox5.Controls.Add(textBox13);
            groupBox5.Controls.Add(textBox12);
            groupBox5.Controls.Add(label14);
            groupBox5.Controls.Add(label13);
            groupBox5.Controls.Add(label12);
            groupBox5.Location = new Point(265, 32);
            groupBox5.Name = "groupBox5";
            groupBox5.Size = new Size(200, 114);
            groupBox5.TabIndex = 6;
            groupBox5.TabStop = false;
            groupBox5.Text = "Move Speed";
            label1.AutoSize = true;
            label1.Location = new Point(12, 26);
            label1.Name = "label1";
            label1.Size = new Size(57, 13);
            label1.TabIndex = 0;
            label1.Text = "Step Ratio";
            label2.AutoSize = true;
            label2.Location = new Point(12, 54);
            label2.Name = "label2";
            label2.Size = new Size(61, 13);
            label2.TabIndex = 1;
            label2.Text = "Pulse Ratio";
            label3.AutoSize = true;
            label3.Location = new Point(12, 83);
            label3.Name = "label3";
            label3.Size = new Size(75, 13);
            label3.TabIndex = 2;
            label3.Text = "Encoder Ratio";
            label4.AutoSize = true;
            label4.Location = new Point(12, 112);
            label4.Name = "label4";
            label4.Size = new Size(82, 13);
            label4.TabIndex = 3;
            label4.Text = "Step Resolution";
            label5.AutoSize = true;
            label5.Location = new Point(17, 26);
            label5.Name = "label5";
            label5.Size = new Size(57, 13);
            label5.TabIndex = 0;
            label5.Text = "Step Ratio";
            label6.AutoSize = true;
            label6.Location = new Point(17, 54);
            label6.Name = "label6";
            label6.Size = new Size(61, 13);
            label6.TabIndex = 1;
            label6.Text = "Pulse Ratio";
            label7.AutoSize = true;
            label7.Location = new Point(17, 83);
            label7.Name = "label7";
            label7.Size = new Size(75, 13);
            label7.TabIndex = 2;
            label7.Text = "Encoder Ratio";
            label8.AutoSize = true;
            label8.Location = new Point(17, 112);
            label8.Name = "label8";
            label8.Size = new Size(82, 13);
            label8.TabIndex = 3;
            label8.Text = "Step Resolution";
            textBox1.Location = new Point(113, 23);
            textBox1.Name = "textBox1";
            textBox1.Size = new Size(81, 20);
            textBox1.TabIndex = 4;
            textBox2.Location = new Point(113, 51);
            textBox2.Name = "textBox2";
            textBox2.Size = new Size(81, 20);
            textBox2.TabIndex = 5;
            textBox3.Location = new Point(113, 77);
            textBox3.Name = "textBox3";
            textBox3.Size = new Size(81, 20);
            textBox3.TabIndex = 6;
            textBox4.Location = new Point(113, 105);
            textBox4.Name = "textBox4";
            textBox4.Size = new Size(81, 20);
            textBox4.TabIndex = 7;
            textBox5.Location = new Point(119, 23);
            textBox5.Name = "textBox5";
            textBox5.Size = new Size(81, 20);
            textBox5.TabIndex = 4;
            textBox6.Location = new Point(119, 54);
            textBox6.Name = "textBox6";
            textBox6.Size = new Size(81, 20);
            textBox6.TabIndex = 5;
            textBox7.Location = new Point(119, 80);
            textBox7.Name = "textBox7";
            textBox7.Size = new Size(80, 20);
            textBox7.TabIndex = 6;
            textBox8.Location = new Point(119, 109);
            textBox8.Name = "textBox8";
            textBox8.Size = new Size(81, 20);
            textBox8.TabIndex = 7;
            label9.AutoSize = true;
            label9.Location = new Point(6, 26);
            label9.Name = "label9";
            label9.Size = new Size(27, 13);
            label9.TabIndex = 0;
            label9.Text = "Low";
            label10.AutoSize = true;
            label10.Location = new Point(6, 53);
            label10.Name = "label10";
            label10.Size = new Size(29, 13);
            label10.TabIndex = 1;
            label10.Text = "High";
            label11.AutoSize = true;
            label11.Location = new Point(6, 81);
            label11.Name = "label11";
            label11.Size = new Size(66, 13);
            label11.TabIndex = 2;
            label11.Text = "Acceleration";
            label12.AutoSize = true;
            label12.Location = new Point(17, 26);
            label12.Name = "label12";
            label12.Size = new Size(27, 13);
            label12.TabIndex = 0;
            label12.Text = "Low";
            label13.AutoSize = true;
            label13.Location = new Point(17, 53);
            label13.Name = "label13";
            label13.Size = new Size(32, 13);
            label13.TabIndex = 1;
            label13.Text = "High ";
            label14.AutoSize = true;
            label14.Location = new Point(17, 81);
            label14.Name = "label14";
            label14.Size = new Size(66, 13);
            label14.TabIndex = 2;
            label14.Text = "Acceleration";
            textBox9.Location = new Point(98, 23);
            textBox9.Name = "textBox9";
            textBox9.Size = new Size(81, 20);
            textBox9.TabIndex = 3;
            textBox10.Location = new Point(98, 53);
            textBox10.Name = "textBox10";
            textBox10.Size = new Size(81, 20);
            textBox10.TabIndex = 4;
            textBox11.Location = new Point(98, 81);
            textBox11.Name = "textBox11";
            textBox11.Size = new Size(81, 20);
            textBox11.TabIndex = 5;
            textBox12.Location = new Point(113, 23);
            textBox12.Name = "textBox12";
            textBox12.Size = new Size(81, 20);
            textBox12.TabIndex = 3;
            textBox13.Location = new Point(113, 50);
            textBox13.Name = "textBox13";
            textBox13.Size = new Size(81, 20);
            textBox13.TabIndex = 4;
            textBox14.Location = new Point(113, 78);
            textBox14.Name = "textBox14";
            textBox14.Size = new Size(81, 20);
            textBox14.TabIndex = 5;
            AutoScaleDimensions = new SizeF(6f, 13f);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(819, 610);
            Controls.Add(groupBox4);
            Controls.Add(groupBox2);
            Controls.Add(groupBox1);
            Controls.Add(button2);
            Controls.Add(button1);
            Name = nameof(GearAndMotorProperties);
            Text = nameof(GearAndMotorProperties);
            groupBox1.ResumeLayout(false);
            groupBox1.PerformLayout();
            groupBox2.ResumeLayout(false);
            groupBox2.PerformLayout();
            groupBox3.ResumeLayout(false);
            groupBox3.PerformLayout();
            groupBox4.ResumeLayout(false);
            groupBox5.ResumeLayout(false);
            groupBox5.PerformLayout();
            ResumeLayout(false);
        }
    }
}