namespace Redbox.Rental.Model.Browse
{
    public enum BrowseFilterType
    {
        AllNewest,
        BluRay,
        ForSale,
        ComingSoon,
        AtoZ,
        DigitalCode,
        Dvd,
        _4KUHD,
        RedboxPlus,
        BackToAll,
        XboxOne,
        Xbox360,
        PS3,
        PS4,
        Wii,
        WiiU,
        NintendoSwitch,
        Top20,
        Action,
        Drama,
        Horror,
        Comedy,
        Family,
        PriceRange,
        _99Cents,
        SonySweepstakes,
        Deals
    }
}