namespace RBA_SDK_ComponentModel
{
    public enum ATTRIBUTE_ID
    {
        SSL_ROOT_CERTIFICATE_FILE,
        SSL_CERTIFICATE_FILE_1,
        SSL_CERTIFICATE_FILE_2,
        SSL_CERTIFICATE_FILE_3,
        SSL_CERTIFICATE_FILE_4,
        SSL_LOCAL_CERTIFICATE_FILE,
        SSL_LOCAL_CERTIFICATE_PASSPHRASE,
        SSL_PRIVATE_KEY_FILE,
        SSL_SECURE_PROTOCOL,
        SSL_SERVER_HANDSHAKE,
        BATTERY_TIMER_INTERVAL_MINUTES,
        PROCESS_MESSAGE_TIMEOUT_SEC,
        DISCOVER_SERVICE_UDP_PORT,
        DISCOVER_SERVICE_UDP_IP,
        MAX_NUMBER_OF_PINGING_DURING_CONNECT,
        TCP_HOST_NAME,
        VALIDATE_MULTI_INSTANCE_CONNECTION,
        WAIT_ACK_TIMEOUT_MSEC,
        ATTRIBUTE_LAST
    }
}